In [1]:
import cv2

In [5]:
eye_cascade=cv2.CascadeClassifier(r"C:\Users\Harsh\Downloads\haarcascade_eye.xml")

In [6]:
face_cascade=cv2.CascadeClassifier(r"C:\Users\Harsh\Downloads\haarcascade_frontalface_alt.xml")

In [10]:
cap=cv2.VideoCapture(0)
while 1:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,255,0),2)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=frame[y:y+h,x:x+w]
        eyes=eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,127,255),2)
        cv2.imshow("My Frame work",frame)
        k=cv2.waitKey(30) & 0xff
    if k==27:
        break
cap.release()
cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np
from tensorflow.keras.models import load_model
from PIL import Image

In [8]:
def face_extractor(img):
    faces=face_cascade.detectMultiScale(img,scaleFactor =1.5, minNeighbors=5)
    if faces is ():
        return None 
    
    
    for (x,y,w,h) in faces:
        cv2.rectangle(img, (x,y),(x+w,y+h),(0,0,255),2)
        roi=img[y:y+h,x:x+w]
    return roi

<>:3: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\Harsh\AppData\Local\Temp\ipykernel_2868\3238051722.py:3: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is ():


In [9]:

model= load_model("mask_nomask_model1.h5")
video_capture=cv2.VideoCapture(0)
while True:
    ret,frame=video_capture.read()
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face=cv2.resize(face,(200,200)) # mapped to images size while training the model
        im=Image.fromarray(face,'RGB')
        img_array=np.array(im)
        img_array=np.expand_dims(img_array,axis=0)
        pred=model.predict(img_array)
        print(pred)
        name = 'None Matching'
        if pred[0][0] > .5:
            name="Masked"
        elif pred[0][1]>.5:
            name='Mask is not there, Put on the mask'
        cv2.putText(frame,name,(75,75),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
    else:
        cv2.putText(frame,"Face not Found",(75,75),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
    cv2.imshow('Video',frame)
    
    if cv2.waitKey(20) & 0xff ==ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 602ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
[[0. 1.]]


In [ ]:
model=load_model("mask_nomask_model1.h5")
results={0:'Mask  found',1:'Mask not found '}
GR_dict={0:(0,255,255),1:(0,255,0)}
rect_size = 4
cap = cv2.VideoCapture(0) 
haarcascade = cv2.CascadeClassifier(r"C:\Users\Harsh\Downloads\haarcascade_frontalface_alt.xml")
while True:
    (rval, im) = cap.read()
    im=cv2.flip(im,1,1)    
    rerect_size = cv2.resize(im, (im.shape[1] // rect_size, im.shape[0] // rect_size))
    faces = haarcascade.detectMultiScale(rerect_size)
    for f in faces:
        (x, y, w, h) = [v * rect_size for v in f] 
        
        face_img = im[y:y+h, x:x+w]
        rerect_sized=cv2.resize(face_img,(200,200))
        normalized=rerect_sized/255.0
        reshaped=np.reshape(normalized,(1,200,200,3))
        reshaped = np.vstack([reshaped])
        result=model.predict(reshaped)       
        label=np.argmax(result,axis=1)[0]   
        cv2.rectangle(im,(x,y),(x+w,y+h),GR_dict[label],2)
        cv2.rectangle(im,(x,y-40),(x+w,y),GR_dict[label],-1)
        cv2.putText(im, results[label], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,0,0),2)

    cv2.imshow('Liv Camera',   im)
    key = cv2.waitKey(10)
    
    if key == 27: # use the escape key
        break
cap.release()
cv2.destroyAllWindows()